name: Build & distribute Android

on:
  push:
    branches: [main]
    paths: ["lib/**"]
  workflow_dispatch:

jobs:
  build-and-distribute:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3

      - name: Install Java
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "zulu"

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: "3.10.5"

      - name: Bump version name & code
        uses: Devofure/advance-android-version-actions@v1.4
        with:
          gradlePath: ./android/app/build.gradle
          versionCode: ${{ github.run_number }}
          versionName: ${{ vars.APP_VERSION }}

      - name: Build APK
        run: |
          flutter --version
          flutter pub get
          flutter build apk --flavor=production

      - name: Upload to Firebase App Distribution
        uses: w9jds/firebase-action@v11.5.0
        with:
          args: appdistribution:distribute ./build/app/outputs/flutter-apk/app-production-release.apk --app ${{ secrets.FIREBASE_ANDROID_APP_ID }} --groups ${{ vars.FIREBASE_TEST_GROUPS }}
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_TOKEN }}
