name: Update Issue Sidebar

on:
  push:
    branches:
      - "issues/*"

jobs:
  update_issue_sidebar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract issue number and branch name
        run: |
          export branch_name=$(echo "${{ github.ref }}" | sed 's/.*\///')

          export issue_number=$branch_name

          echo "Issue Number: $issue_number"
          echo "Branch Name: $branch_name"

          echo "issue_number='$issue_number'" >> $GITHUB_ENV
          echo "branch_name='$branch_name'" >> $GITHUB_ENV

      - name: Find open issue by number
        id: find_issue
        run: |
          response=$(curl -s -X GET \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ env.issue_number }})
          echo "$response" > issue.json
          echo "id='${{ env.issue_number }})'" >> "$GITHUB_OUTPUT"

      - name: Update issue sidebar
        if: steps.find_issue.outputs.id != ''
        run: |
          cat issue.json
          # echo issue.json
          # issueId=$(jq -r '.id' issue.json)
          # requestBody="{ \"body\": \"This branch is linked to [issue ${{ env.issue_number }}](issues/${{ env.branch_name }}).\" }"
          # curl -s -X PATCH \
          #   -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          #   -H "Accept: application/vnd.github.v3+json" \
          #   -H "Content-Type: application/json" \
          #   -d "$requestBody" \
          #   https://api.github.com/repos/${{ github.repository }}/issues/${{ env.issue_number }}
