name: Add issue link
on:
  pull_request:
    types: [opened]

jobs:
  issue-links:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: tkt-actions/add-issue-links@v1.8.1
        with:
          header: Issue
          position: top
          resolve: true
          branch-prefix: "issues/"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
